### ISSUE TITLE
請問有可能用 git 描述中的特定文字當 trigger 嗎 ?

### ISSUE THREAD

**Issue by andrew781026** [kylemocode/actions-deploy-sample#1]
最近在研究 github-action , 翻了許多資料看到的都是 push 或 pull_request 當作 Trigger , 

```yaml
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
```

請問有可能用 git 描述中的特定文字當 trigger 嗎 ? 

> 舉例 : 

我 commit 時在 Git Commit Message 中寫上  `**AI部屬**`  然後 github-action 就將 Jobs 作執行
